[server]
port = 8501 # change port number. By default streamlit uses 8501 port
address = "localhost"

headless=true # This will eliminate automatically open browser
# enableCORS=false
# enableXsrfProtection=false
# enableWebsocketCompression=false
[browser] # This ip and port will show in command prompt
serverAddress = "localhost"
serverPort = 8501
